config/routes.rb
Rails.application.routes.draw do

  match "/admin", to: "admin#index", :via => 'get'

  devise_for :users

  root :to => 'home#index'

  resources :admin do
    get 'change_to_admin'
    get 'change_to_guest'
    get 'change_to_read_only'
    get 'change_to_read_write'
    get 'remove_user'
  end

  resources :evaluation do
    get  'import',       on: :collection
    get  'import_gpr',   on: :collection
    get  'export',       on: :member
    get  'missing_data', on: :collection

    post 'upload',       on: :collection
    post 'upload_gpr',   on: :collection
  end

  resources :instructor do
    get 'export', on: :member
  end

  resources :course_name

end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
  belongs_to :instructor
  validates_associated :instructor

  validates :term, presence: true, format: { with: /\A[12][0-9]{3}[A-Z]\z/,
    message: "must be in the format: xxxxY where xxxx is year and Y is semester letter. Example: 2015C" }
  validates :subject, presence: true, format: { with: /\A[A-Z]{4}\z/,
    message: "must be four capital letters." }
  validates :course, presence: true, numericality: { only_integer: true }
  validates :section, presence: true, numericality: { only_integer: true }
  validates :enrollment, numericality: { only_integer: true, allow_blank: true }
  validates :item1_mean, numericality: { allow_blank: true }
  validates :item2_mean, numericality: { allow_blank: true }
  validates :item3_mean, numericality: { allow_blank: true }
  validates :item4_mean, numericality: { allow_blank: true }
  validates :item5_mean, numericality: { allow_blank: true }
  validates :item6_mean, numericality: { allow_blank: true }
  validates :item7_mean, numericality: { allow_blank: true }
  validates :item8_mean, numericality: { allow_blank: true }

  scope :no_missing_data, -> {where.not("instructor_id is NULL OR enrollment is NULL OR item1_mean is NULL OR item2_mean is NULL OR item3_mean is NULL OR item4_mean is NULL OR item5_mean is NULL OR item6_mean is NULL OR item7_mean is NULL OR item8_mean is NULL")}
  scope :missing_data, -> {where("instructor_id is NULL OR enrollment is NULL OR item1_mean is NULL OR item2_mean is NULL OR item3_mean is NULL OR item4_mean is NULL OR item5_mean is NULL OR item6_mean is NULL OR item7_mean is NULL OR item8_mean is NULL OR gpr is NULL")}

  KEY_ATTRIBUTES = [:term, :subject, :course, :section].freeze

  def self.key_attributes
    KEY_ATTRIBUTES
  end

  def self.create_if_needed_and_update(key_attrs, other_attrs)
    if other_attrs[:instructor].is_a?(String)
      lst_name = other_attrs[:instructor].split.first
      fst_name = other_attrs[:instructor].split.last
      search_str1 = lst_name + "%" + " " + fst_name + "%"
      search_str2 = fst_name + "%" + " " + lst_name + "%"
      if Instructor.where('name like ?', search_str1).length != 0
        other_attrs[:instructor_id] = Instructor.where('name like ?', search_str1).first.id
      elsif Instructor.where('name like ?', search_str2).length != 0
        other_attrs[:instructor_id] = Instructor.where('name like ?', search_str2).first.id
      else
        other_attrs[:instructor_id] = Instructor.where(name: Instructor.normalize_name(other_attrs[:instructor])).create.id
      end
      other_attrs.delete(:instructor)
    end

    evaluation = where(key_attrs).first_or_initialize
    is_new_record = evaluation.new_record?
    evaluation.save

    evaluation.update(other_attrs)

    [ evaluation, is_new_record ]
  end

  def self.default_sorted_groups
    # We group by the following things and then sort the groups in this order:
    #  - Term (2015C, 2015A, 2014C)
    #  - Subject (CSCE, ENGR)
    #  - Course (110, 111, 121)
    #  - Instructor (Williams, Hurley)
    #  - First character of section (200s, 500s are grouped together)
    all.group_by do |eval|
      eval.term.to_s + eval.subject.to_s + eval.course.to_s + eval.instructor.try(:id).to_s + eval.section.to_s[0]
    end.sort { |group1, group2| group1.first <=> group2.first }.map(&:last)
  end

  def key
    attributes.select { |k, _| Evaluation.key_attributes.include? k.to_sym }
  end

  def is_honors_section?
    section.to_s.starts_with?("2")
  end

  def subject_course
    "#{subject} #{course}"
  end

  def has_course_name?
    !course_name.nil?
  end

  def course_name
    CourseName.where(subject_course: subject_course).first.try(:name)
  end

  def csv_data
    [
      term,
      subject,
      course,
      section,
      instructor.name,
      enrollment,
      item1_mean,
      item2_mean,
      item3_mean,
      item4_mean,
      item5_mean,
      item6_mean,
      item7_mean,
      item8_mean
    ].map(&:to_s)
  end

end

app/controllers/evaluation_controller.rb
class EvaluationController < ApplicationController

  before_action :authenticate_user!

  def new
    @evaluation = Evaluation.new
    @instructors = Instructor.select_menu_options
    render layout: "layouts/centered_form"
  end

  def create
    key_attrs, other_attrs = split_attributes(evaluation_params)

    @evaluation = Evaluation.where(key_attrs).first_or_initialize
    @evaluation.assign_attributes(other_attrs)
    @evaluation.save

    if @evaluation.errors.empty?
      flash[:notice] = "Evaluation created."
      redirect_to evaluation_index_path(term: @evaluation.term)
    else
      flash[:errors] = @evaluation.errors
      @instructors = Instructor.select_menu_options
      render 'new', layout: "layouts/centered_form"
    end
  end

  def index
    latest_term = params[:term] || Evaluation.no_missing_data.pluck(:term).uniq.sort.reverse.first
    if latest_term.nil?
      flash[:notice] = "No evaluation data exists yet! Try importing some."
      redirect_to root_path
    else
      redirect_to evaluation_path(id: latest_term)
    end
  end

  def show
    term = params[:id] || Evaluation.no_missing_data.pluck(:term).uniq.sort.reverse.first
    @evaluation_groups = Evaluation.no_missing_data.where(term: term).default_sorted_groups
    @terms = Evaluation.pluck(:term).uniq.sort.reverse
  end

  def missing_data
    @evaluation_groups = Evaluation.missing_data.default_sorted_groups
  end

  def import
    render layout: "layouts/centered_form"
  end

  def import_gpr
    render layout: "layouts/centered_form"
  end

  def export
    term = params.require(:id)
    evaluation_groups = Evaluation.no_missing_data.where(term: term).default_sorted_groups
    send_data EvaluationReportExporter.new(evaluation_groups).generate, filename: "#{term}_evaluation_report_#{Time.now.strftime('%F')}.csv"
  end

  def edit
    @evaluation = Evaluation.find(evaluation_id)
    @instructors = Instructor.select_menu_options
    render layout: "layouts/centered_form"
  end

  def update
    @evaluation = Evaluation.find(evaluation_id)
    @evaluation, _ = Evaluation.create_if_needed_and_update(@evaluation.key, evaluation_params)
    if @evaluation.errors.empty?
      flash[:notice] = "Evaluation updated."
      redirect_to evaluation_path(id: @evaluation.term)
    else
      flash[:errors] = @evaluation.errors
      render 'edit'
    end
  end

  def upload
    if params[:data_file] != nil
      importer = ::PicaReportImporter.new(params.require(:data_file).tempfile)
      importer.import
      results = importer.results

      flash[:notice] = "#{results[:created]} new evaluations imported. #{results[:updated]} evaluations updated. #{results[:failed]} evaluations were not imported."
      redirect_to evaluation_index_path
    else
      flash[:errors] = "File not attached, please select file to upload"
      redirect_to import_evaluation_index_path
    end
  rescue ::PicaReportImporter::MalformedFileException => ex
    flash[:errors] = ex.to_s
    redirect_to import_evaluation_index_path
  rescue
    flash[:errors] = "There was an error parsing that XLSX file. Maybe it is corrupt? Please note that only XLSX files are supported, not XLS."
    redirect_to import_evaluation_index_path
  end

  def upload_gpr
    unless params[:term] && params[:term].match(/\A[12][0-9]{3}[A-Z]\z/)
      flash[:errors] = "Term is either missing or in the incorrect format."
      redirect_to import_gpr_evaluation_index_path
      return
    end

    if params[:data_file].nil?
      flash[:errors] = "File not attached, please select file to upload"
      redirect_to import_gpr_evaluation_index_path
      return
    end

    importer = ::GradeDistributionReportImporter.new(params.require(:data_file).tempfile, params[:term])
    importer.import
    results = importer.results

    flash[:notice] = "#{results[:created]} new GPRs imported. #{results[:updated]} evaluation GPRs updated. #{results[:failed]} evaluation GPRs were not imported."
    redirect_to evaluation_index_path
  rescue PDF::Reader::MalformedPDFError => ex
    flash[:errors] = "There was an error parsing that PDF file. Maybe it is corrupt?"
    redirect_to import_gpr_evaluation_index_path
  end

  private
  def split_attributes(all_attrs)
      # key attributes are ones for which we should have one unique record for a set of them
      key_attributes = all_attrs.select { |k,v| Evaluation.key_attributes.include?(k.to_sym) }

      # other atttributes are ones that should either be assigned or updated
      other_attributes = all_attrs.reject { |k,v| Evaluation.key_attributes.include?(k.to_sym) }
      if other_attributes[:instructor] && !other_attributes[:instructor].instance_of?(Instructor) && !other_attributes[:instructor].empty?
        other_attributes[:instructor] = Instructor.where(name: other_attributes[:instructor]).first_or_create
      elsif other_attributes[:instructor_id] && other_attributes[:instructor_id] != "0"
        other_attributes[:instructor] = Instructor.where(id: other_attributes[:instructor_id]).first
        other_attributes.delete(:instructor_id)
      end

      [ key_attributes, other_attributes ]
  end

  def evaluation_params
    params.require(:evaluation).permit(:term, :subject, :course, :section, :instructor_id,
      :enrollment, :item1_mean, :item2_mean, :item3_mean, :item4_mean, :item5_mean,
      :item6_mean, :item7_mean, :item8_mean, :instructor, :gpr)
  end

  def evaluation_id
    params.require(:id)
  end
end

app/helpers/evaluation_helper.rb
module EvaluationHelper
end

app/views/evaluation/_enrollment.html.haml
%label{for: "evaluation_enrollment", class: "col-sm-2 control-label"} Enrollment
.col-sm-4
 = f.text_field  :enrollment, class: "form-control", placeholder: "e.g. 50"

app/views/evaluation/_items.html.haml
.form-group
  %label{for: "evaluation_item1_mean", class: "col-sm-2 control-label"} Item 1 Mean
  .col-sm-4
    = f.text_field :item1_mean, class: "form-control", placeholder: "e.g. 4.32"

  %label{for: "evaluation_item2_mean", class: "col-sm-2 control-label"} Item 2 Mean
  .col-sm-4
    = f.text_field :item2_mean, class: "form-control", placeholder: "e.g. 4.32"

.form-group
  %label{for: "evaluation_item3_mean", class: "col-sm-2 control-label"} Item 3 Mean
  .col-sm-4
    = f.text_field :item3_mean, class: "form-control", placeholder: "e.g. 4.32"

  %label{for: "evaluation_item4_mean", class: "col-sm-2 control-label"} Item 4 Mean
  .col-sm-4
    = f.text_field :item4_mean, class: "form-control", placeholder: "e.g. 4.32"

.form-group
  %label{for: "evaluation_item5_mean", class: "col-sm-2 control-label"} Item 5 Mean
  .col-sm-4
    = f.text_field :item5_mean, class: "form-control", placeholder: "e.g. 4.32"

  %label{for: "evaluation_item6_mean", class: "col-sm-2 control-label"} Item 6 Mean
  .col-sm-4
    = f.text_field :item6_mean, class: "form-control", placeholder: "e.g. 4.32"

.form-group
  %label{for: "evaluation_item7_mean", class: "col-sm-2 control-label"} Item 7 Mean
  .col-sm-4
    = f.text_field :item7_mean, class: "form-control", placeholder: "e.g. 4.32"

  %label{for: "evaluation_item8_mean", class: "col-sm-2 control-label"} Item 8 Mean
  .col-sm-4
    = f.text_field :item8_mean, class: "form-control", placeholder: "e.g. 4.32"

app/views/evaluation/edit.html.haml
%h1 Evaluation data:

= javascript_include_tag 'evaluation', 'data-turbolinks-track' => true
= form_for @evaluation, method: :put, html: { class: "form-horizontal" } do |f|
  .form-group
    %label.col-sm-2.control-label Term
    .col-sm-4
      %p.form-control-static= @evaluation.term

    %label{for: "evaluation_subject", class: "col-sm-2 control-label"} Subject
    .col-sm-4
      %p.form-control-static= @evaluation.subject

  .form-group
    %label{for: "evaluation_course", class: "col-sm-2 control-label"} Course
    .col-sm-4
      %p.form-control-static= @evaluation.course

    %label{for: "evaluation_section", class: "col-sm-2 control-label"} Section
    .col-sm-4
      %p.form-control-static= @evaluation.section

  .form-group
    = render partial: 'evaluation/enrollment.html.haml', :locals => {:f => f}

    #instructor_select_wrapper
      %label{for: "evaluation_instructor_id", class: "col-sm-2 control-label"} Instructor
      .col-sm-4
        = f.select "instructor_id", @instructors, {}, class: "form-control"

    #instructor_name_wrapper{style: "display: none"}
      %label{for: "evaluation_instructor", class: "col-sm-2 control-label"} Name
      .col-sm-4
        = f.text_field :instructor, class: "form-control", placeholder: "e.g. Walter Daugherity", value: nil
        %p.help-block
          %a#cancel_manual_instructor_entry{href: "#"} Cancel

  = render partial: 'evaluation/items.html.haml', :locals => {:f => f}

  .form-group
    %label{for: "evaluation_gpr", class: "col-sm-2 control-label"} GPR
    .col-sm-4
      = f.text_field :gpr, class: "form-control", placeholder: "e.g. 4.0"

  .form-group
    .col-sm-10.col-sm-offset-2
      = f.submit "Edit Evaluation", class: "btn btn-primary"

app/views/evaluation/import.html.haml
%h1 Import evaluation data from PICA

= form_tag({action: :upload}, multipart: true) do
  .form-group
    %label{ for: "data_file" } Data File
    = file_field_tag 'data_file'
  = submit_tag 'Upload', class: "btn btn-primary"
  

app/views/evaluation/import_gpr.html.haml
%h1 Import GPR distribution data from the TAMU registrar

= form_tag({action: :upload_gpr}, multipart: true) do
  .form-group
    %label{ for: "term"} Term
    = text_field_tag "term", nil, placeholder: "e.g. 2015C", class: "form-control"
  .form-group
    %label{ for: "data_file"} Data File
    = file_field_tag 'data_file'
  .form-group
    = submit_tag 'Upload', class: "btn btn-primary"

app/views/evaluation/index.html.haml
%p.text-right
  .pull-right
    = link_to "Import PICA Data", import_evaluation_index_path, class: "btn btn-primary"
    = link_to "Export This Report", export_evaluation_index_path, class: "btn btn-primary"
  = form_tag evaluation_index_path, method: :get, class: "form-inline" do
    .form-group
      %label{ for: "term" } Select Term:
      = select "term", "selection", @terms, {}, class: "form-control"

%table.table.table-condensed
  %thead
    %tr
      %th Edit
      %th Term
      %th Subject
      %th Course
      %th Section
      %th Instructor
      %th Enrollment
      - (1..8).each do |num|
        %th
          = "Item #{num} mean"
      %th Mean Student Eval Score
      %th Course Level Average

  %tbody
    - @evaluation_groups.each do |group|
      - group.each do |evaluation|
        %tr
          %td
            = link_to "Edit", edit_evaluation_path(evaluation)
          %td
            = evaluation.term
          %td
            = evaluation.subject
          %td
            = evaluation.course
          %td
            = evaluation.section
          %td
            = link_to evaluation.instructor.name, instructor_path(id: evaluation.instructor.id)
          %td
            = evaluation.enrollment
          - (1..8).each do |num|
            %td
              = evaluation.method("item#{num}_mean".to_sym).call
          %td{colspan: 2}
      %tr
        %td{colspan: 6}
        %td= compute_total_enrollment(group)
        - (1..8).each do |x|
          %td.highlighted= compute_weighted_average_for_item(x, group).round(2)
        %td.green-highlight= compute_mean_student_eval_score(group).round(2)
        %td.green-highlight= compute_course_level_average(group, @evaluation_groups).round(2)
      %tr
        %td{colspan: 17}

app/views/evaluation/missing_data.html.haml
%p.text-right
  .pull-right
    - if can? :write, :all
      = link_to "Import PICA Data", import_evaluation_index_path, class: "btn btn-primary"

%table.table.table-condensed
  %thead
    %tr
      - if can? :write, :all
        %th Edit
      %th Term
      %th Subject
      %th Course
      %th Section
      %th Instructor
      %th Enrollment
      - (1..8).each do |num|
        %th
          = "Item #{num} mean"
      %th GPR

  %tbody
    - @evaluation_groups.each do |group|
      - group.each do |evaluation|
        %tr
          - if can? :write, :all
            %td
              = link_to "Edit", edit_evaluation_path(evaluation)
          %td{ class: (evaluation.term.nil? ? "highlighted" : "" ) }
            = evaluation.term
          %td{ class: (evaluation.subject.nil? ? "highlighted" : "" ) }
            = evaluation.subject
          %td{ class: (evaluation.course.nil? ? "highlighted" : "" ) }
            = evaluation.course
          %td{ class: (evaluation.section.nil? ? "highlighted" : "" ) }
            = evaluation.section
          %td{ class: (link_to evaluation.instructor.name, instructor_path(id: evaluation.instructor.id).nil? ? "highlighted" : "" ) }
            = link_to evaluation.instructor.name, instructor_path(id: evaluation.instructor.id)
          %td{ class: (evaluation.enrollment.nil? ? "highlighted" : "" ) }
            = evaluation.enrollment
          - (1..8).each do |num|
            %td{ class: (evaluation.method("item#{num}_mean".to_sym).call.nil? ? "highlighted" : "" ) }
              = evaluation.method("item#{num}_mean".to_sym).call
          %td{ class: (evaluation.gpr.nil? ? "highlighted" : "" ) }
            = evaluation.gpr
      %tr
        %td{colspan: 16}

app/views/evaluation/new.html.haml
%h1 Evaluation data:
= javascript_include_tag 'evaluation', 'data-turbolinks-track' => true


= form_for :evaluation, url: evaluation_index_path, method: :post, html: { class: "form-horizontal" } do |f|
  .form-group
    %label{for: "evaluation_term", class: "col-sm-2 control-label"} Term
    .col-sm-4
      = f.text_field :term, class: "form-control", placeholder: "e.g. 2015C", required: true

    %label{for: "evaluation_subject", class: "col-sm-2 control-label"} Subject
    .col-sm-4
      = f.text_field :subject, class: "form-control", placeholder: "e.g. CSCE", required: true

  .form-group
    %label{for: "evaluation_course", class: "col-sm-2 control-label"} Course
    .col-sm-4
      = f.text_field :course, class: "form-control", placeholder: "e.g. 121", required: true

    %label{for: "evaluation_section", class: "col-sm-2 control-label"} Section
    .col-sm-4
      = f.text_field :section, class: "form-control", placeholder: "e.g. 501", required: true

  .form-group
    = render partial: 'evaluation/enrollment.html.haml', :locals => {:f => f}

    #instructor_select_wrapper
      %label{for: "evaluation_instructor_id", class: "col-sm-2 control-label"} Instructor
      .col-sm-4
        = f.select "instructor_id", @instructors, {}, class: "form-control"
    #instructor_name_wrapper{style: "display: none"}
      %label{for: "evaluation_instructor", class: "col-sm-2 control-label"} Name
      .col-sm-4
        = f.text_field :instructor, class: "form-control", placeholder: "e.g. Walter Daugherity"
        %p.help-block
          %a#cancel_manual_instructor_entry{href: "#"} Cancel

  = render partial: 'evaluation/items.html.haml', :locals => {:f => f} 
  .form-group
    .col-sm-10.col-sm-offset-2
      = f.submit "Add Evaluation", class: "btn btn-primary"

app/views/evaluation/show.html.haml
%p.text-right
  .pull-right
    - if can? :write, :all
      = link_to "Import PICA Data", import_evaluation_index_path, class: "btn btn-primary"
    = link_to "Export This Report", export_evaluation_path, class: "btn btn-primary"
    = link_to "Missing Data", missing_data_evaluation_index_path, class: "btn btn-primary"
  = form_tag evaluation_index_path, method: :get, class: "form-inline" do
    .form-group
      %label{for: "term"} Select Term:
      %select{name: "term", id: "term", class: "form-control"}
        - @terms.each do |term|
          %option{value: term, selected: (term == params[:id] ? "selected" : nil)}= term
    %button{type: "submit", class: "btn btn-primary"} Go

%table.table.table-condensed
  %thead
    %tr
      - if can? :write, :all
        %th Edit
      %th Term
      %th Subject
      %th Course
      %th Section
      %th Instructor
      %th Enrollment
      - (1..8).each do |num|
        %th
          = "Item #{num} mean"
      %th Mean Student Eval Score
      %th Course Level Average

  %tbody
    - @evaluation_groups.each do |group|
      - group.each do |evaluation|
        %tr
          - if can? :write, :all
            %td
              = link_to "Edit", edit_evaluation_path(evaluation)
          %td
            = evaluation.term
          %td
            = evaluation.subject
          %td
            = evaluation.course
          %td
            = evaluation.section
          %td
            = link_to evaluation.instructor.name, instructor_path(id: evaluation.instructor.id)
          %td
            = evaluation.enrollment
          - (1..8).each do |num|
            %td
              = evaluation.method("item#{num}_mean".to_sym).call
          %td{colspan: 2}
      %tr
        %td{colspan: 6}
        %td= compute_total_enrollment(group)
        - (1..8).each do |x|
          %td.highlighted= compute_weighted_average_for_item(x, group).round(2)
        %td.green-highlight= compute_mean_student_eval_score(group).round(2)
        %td.green-highlight= compute_course_level_average(group, @evaluation_groups).round(2)
      %tr
        %td{colspan: 17}