config/routes.rb
Rails.application.routes.draw do

  match "/admin", to: "admin#index", :via => 'get'

  devise_for :users

  root :to => 'home#index'

  resources :admin do
    get 'change_to_admin'
    get 'change_to_guest'
    get 'change_to_read_only'
    get 'change_to_read_write'
    get 'remove_user'
  end

  resources :evaluation do
    get  'import',       on: :collection
    get  'import_gpr',   on: :collection
    get  'export',       on: :member
    get  'missing_data', on: :collection

    post 'upload',       on: :collection
    post 'upload_gpr',   on: :collection
  end

  resources :instructor do
    get 'export', on: :member
  end

  resources :course_name

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "home"
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.outer
  .middle
    .inner.text-center
      %h1 PICA Utilities
      - if user_signed_in?
        - if can? :manage, :all
          %p= link_to "User management panel", admin_index_path, class: "btn btn-primary"
        -if can? :write, :all
          %p= link_to "Import evaluation data from PICA", import_evaluation_index_path, class: "btn btn-primary"
          %p= link_to "Import GPR distribution data", import_gpr_evaluation_index_path, class: "btn btn-primary"
          %p= link_to "Add Paper Evaluation", new_evaluation_path, class: "btn btn-primary"
        - if can? :read, :all
          %p= link_to "View Evaluation Data", evaluation_index_path, class: "btn btn-primary"
          %p= link_to "View Missing Data", missing_data_evaluation_index_path, class: "btn btn-primary"
          %p= link_to "Faculty Member Historical Data", instructor_index_path, class: "btn btn-primary"
        - else
          %p= "please ask an administrator to authorize your account"
        %p= link_to "Sign out", destroy_user_session_path, method: :delete
      - else
        %p= link_to "Sign In To Begin", new_user_session_path, class: "btn btn-primary"