config/routes.rb
Rails.application.routes.draw do

  match "/admin", to: "admin#index", :via => 'get'

  devise_for :users

  root :to => 'home#index'

  resources :admin do
    get 'change_to_admin'
    get 'change_to_guest'
    get 'change_to_read_only'
    get 'change_to_read_write'
    get 'remove_user'
  end

  resources :evaluation do
    get  'import',       on: :collection
    get  'import_gpr',   on: :collection
    get  'export',       on: :member
    get  'missing_data', on: :collection

    post 'upload',       on: :collection
    post 'upload_gpr',   on: :collection
  end

  resources :instructor do
    get 'export', on: :member
  end

  resources :course_name

end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  has_many :evaluations

  validates :name, presence: true, uniqueness: true

  def course_section_groups
    evaluations.no_missing_data.default_sorted_groups
  end

  def self.select_menu_options
    # pluck call must remain :name, :id to have the correct ordering for the select box helper
    order(:name).pluck(:name, :id).push([ "New instructor...", 0 ])
  end

  def self.normalize_name(name)
    return nil unless name
    name.split.map(&:capitalize).join(" ")
  end
end

app/controllers/instructor_controller.rb
class InstructorController < ApplicationController

  before_action :authenticate_user!
  before_action :verify_read

  def index
    # return the instructors in sorted order by last name
    instructors_with_enrollment_data = Evaluation.no_missing_data.pluck(:instructor_id).uniq
    @instructors =Instructor.where(id: instructors_with_enrollment_data).sort { |a, b| a.name.split(" ").last <=> b.name.split(" ").last }
  end

  def show
    @instructor = Instructor.find(id)
    @evaluation_groups = Evaluation.no_missing_data.default_sorted_groups
  end

  def export
    instructor = Instructor.find(id)
    evaluation_groups = Evaluation.no_missing_data.default_sorted_groups
    send_data InstructorReportExporter.new(instructor,evaluation_groups).generate, filename: "#{instructor.name}_instructor_report_#{Time.now.strftime('%F')}.csv"
  end

  private
  def id
    params.require(:id)
  end

  def verify_read
    unless can? :read, :all
      redirect_to root_path
    end
  end
end

app/helpers/instructor_helper.rb
module InstructorHelper
  def course_name_for(course)
    course.subject_course + (course.is_honors_section? ? "H" : "")
  end
end

app/views/instructor/index.html.haml
%h1 Instructors
%p (Sorted by last name)
.row
  - @instructors.each_slice(@instructors.size / 3 + 1).each do |slice|
    .col-md-4
      %ul
        - slice.each do |instructor|
          %li= link_to instructor.name, instructor_path(id: instructor.id)

app/views/instructor/show.html.haml
%p.text-right
  = link_to "Download", export_instructor_path, class: "btn btn-primary"

%h1
  = @instructor.name

%table.table.table-bordered.table-condensed
  %thead
    %tr
      %th Undergraduate and Graduate Courses Taught
      %th Semester
      %th No. of Students Enrolled
      %th Mean Student Evaluation Score
      %th Dept Avg Student Evaluation Score for Equivalent Level Courses
      %th Avg. Numerical Grade Earned by Students
      %th Avg. Course Level Numerical Grade
  %tbody
    - @instructor.course_section_groups.each do |course_section_group|
      %tr
        %td
          = course_name_for(course_section_group.first)
          = (course_section_group.first.has_course_name? ? course_section_group.first.course_name : link_to("Add Course Name", new_course_name_path(subject_course: course_section_group.first.subject_course, return_to: instructor_path(@instructor))))
        %td= course_section_group.first.term
        %td= compute_total_enrollment(course_section_group)
        %td= compute_mean_student_eval_score(course_section_group).round(2)
        %td= compute_course_level_average(course_section_group, @evaluation_groups).round(2)
        %td= compute_mean_gpr(course_section_group).try(:round, 2)
        %td= compute_course_level_mean_gpr(course_section_group, @evaluation_groups).try(:round, 2)

  %tfoot
  / blank table row
  %tr
    %td{colspan: 4}

  %tr
    %td{colspan: 2} TOTAL NUMBER OF STUDENTS
    %td{colspan: 2}= @instructor.course_section_groups.map { |course_section_group| compute_total_enrollment(course_section_group) }.reduce(:+)